name: language_translator
description: Language Translator using Google ML Kit
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  translator: ^0.1.7
  camera: ^0.10.3+2
  speech_to_text: ^6.1.1
  flutter_share: ^2.0.0
  flutter_tts: ^3.6.3
  image_picker: ^0.8.7
  google_ml_kit: ^0.13.0
  google_mlkit_text_recognition: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
